name: navigation

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  vrouter: ^1.2.1

  authorization:
    path: ../features/authorization
  catalog:
    path: ../features/catalog
  home:
    path: ../features/home
  settings:
    path: ../features/settings

dev_dependencies:
  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.15.2
