name: home

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  data:
    path: ../../data
  navigation:
    path: ../../navigation

dev_dependencies:
  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.15.2
